name: CI
on: [push, pull_request]
jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.0' }
      - run: composer install --no-interaction --no-progress
      - run: composer cs

